TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Dotpulse.OutdatedBrowser': true


Dotpulse:
  OutdatedBrowser:
    includeJavascript: true
    includeJavascriptCall: true
    includeCSS: true
    includeHTML: true
    fallbackLanguage: en
    # Browser based: IE8, IE9, IE10, IE11 or Edge
    # Feature based: Flexbox, oldGrid or Grid
    # Property based: Any CSS property
    lowerThan: oldGrid
    target: _blank
