Neos:
  Neos:
    fusion:
      autoInclude:
        'Dotpulse.OutdatedBrowser': true

Dotpulse:
  OutdatedBrowser:
    javascript:
      # Set to `Storage` or `Cookie`
      implementation: Storage
      include: true
      inline: true
    css:
      include: true
      inline: true
    fallbackLanguage: en
    # Browser based: A23, IE8, IE9, IE10, IE11 or Edge
    # Feature based: Flexbox, oldGrid or Grid
    # Property based: Any CSS property
    lowerThan: Edge
    target: _blank
