Neos:
  Neos:
    fusion:
      autoInclude:
        'Dotpulse.OutdatedBrowser': true


Dotpulse:
  OutdatedBrowser:
    javascript:
      include: true
      inline: true
    css:
      include: true
      inline: true
    fallbackLanguage: en
    # Browser based: A23, IE8, IE9, IE10, IE11 or Edge
    # Feature based: Flexbox, oldGrid or Grid
    # Property based: Any CSS property
    lowerThan: IE11
    target: _blank
